const sql = require('mssql');

const TutorSetup = {
    SID: sql.Int,
    Photo: sql.VarChar(sql.MAX),
    Video: sql.VarChar(sql.MAX),
    FirstName: sql.VarChar(255),
    MiddleName: sql.VarChar(255),
    LastName: sql.VarChar(255),
    Address1: sql.VarChar(255),
    Address2: sql.VarChar(255),
    CityTown: sql.VarChar(255),
    StateProvince: sql.VarChar(255),
    ZipCode: sql.VarChar(20),
    Country: sql.VarChar(100),
    CellPhone: sql.VarChar(20),
    GMT: sql.VarChar(10),
    ResponseHrs: sql.VarChar(10),
    TutorScreenname: sql.VarChar(255),
    HeadLine: sql.VarChar(255),
    Introduction: sql.VarChar(sql.MAX),
    Motivate: sql.VarChar(sql.MAX),
    IdVerified: sql.VarChar(10),
    BackgroundVerified: sql.VarChar(10),
    AcademyId: sql.VarChar(100),
    Grades: sql.VarChar(100),
    userId: sql.VarChar(100),
    disableDates: sql.VarChar(sql.MAX),
    disableWeekDays: sql.VarChar(sql.MAX),
    enableHourSlots: sql.VarChar(sql.MAX),
    disableHourSlots: sql.VarChar(sql.MAX),
    enabledDays: sql.VarChar(sql.MAX),
    addedDisabledHours: sql.Bit,
    disableHoursRange: sql.VarChar(sql.MAX),
    disableColor: sql.VarChar(10),
    Online: sql.Bit,
    AgreementDate: sql.DateTime,
    VacationMode: sql.Bit,
    StartVacation: sql.DateTimeOffset,
    EndVacation: sql.DateTimeOffset,
    Step: sql.Int,
    Status: sql.VarChar(20),
    CreatedAT: sql.DateTime,
    IsVideoRecorded: sql.Bit,
    CertificateExpiration: sql.DateTime,
    NativeLang: sql.VarChar(100),
    NativeLangState: sql.VarChar(100),
    NativeLangOtherLang: sql.NVarChar(sql.MAX),
    WorkExperience: sql.NVarChar(sql.MAX),
    ThingsReferences: sql.NVarChar(sql.MAX),
    DegreeFile: sql.NVarChar(sql.MAX),
    CertificateFile: sql.NVarChar(sql.MAX),
    Resume: sql.VarChar(100),
    CertFileName: sql.VarChar(100),
    DegFileName: sql.VarChar(100),
};

module.exports = TutorSetup;
